# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2.0'

    - name: Build
      run: |
        cd AllEyesOnMe
        xcodebuild build -project AllEyesOnMe.xcodeproj -scheme AllEyesOnMe clean build -sdk iphonesimulator CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        cd AllEyesOnMe
        xcodebuild test -project AllEyesOnMe.xcodeproj -scheme AllEyesOnMe clean build -sdk iphonesimulator -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro" CODE_SIGNING_ALLOWED=No
